name: Release Next

on:
  workflow_run:
    workflows: [Release Stable]
    types: [completed]
    branches: [main]

jobs:
  main:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: NPM registry authentication
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: pnpm i

      - run: pnpm run changeset:version --snapshot next
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: pnpm run changeset:publish --tag next
